name: manual-versioning
on:
  workflow_dispatch:
    inputs:
      levelBump:
        description: "Version level bump to apply (e.g., auto, patch, minor, major)."
        required: true
        default: "auto"
        type: choice
        options:
          - "auto"
          - "patch"
          - "minor"
          - "major"
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Python Semantic Release (Automatic)
        if: github.event.inputs.levelBump == 'auto'
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          verbosity: 2

      - name: Python Semantic Release (Manual)
        if: github.event.inputs.levelBump != 'auto'
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: ${{ github.event.inputs.levelBump }}
          verbosity: 2
