name: manual-versioning
on:
  workflow_dispatch:
    inputs:
      levelBump:
        description: "Version level bump to apply (e.g., auto, patch, minor, major)."
        required: true
        default: "auto"
        type: choice
        options:
          - "auto"
          - "patch"
          - "minor"
          - "major"
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Python Semantic Release (Automatic)
        if: github.event.inputs.levelBump == 'auto'
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          verbosity: 2

      - name: Python Semantic Release (Manual)
        if: github.event.inputs.levelBump != 'auto'
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          force: ${{ github.event.inputs.levelBump }}
          verbosity: 2
