name: Validate the renovate configuration

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/renovate.json5'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: '*.json5'
